#https://docs.github.com/en/actions/guides/publishing-docker-images
name: Publish f5-devops-base image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push f5-devops-base to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vinnie357/f5-devops-base
          file: f5-devops-base/Dockerfile
          tag_with_ref: true
